export {default as HomePageComponent} from './homePageComponent/HomePageComponent'
export {default as CoursesPageComponent} from './coursesPageComponent/CoursesPageComponent'
export {default as BooksPageComponent} from './booksPageComponent/BooksPageComponent'
export {default as ArticlePageComponent} from './articlePageComponent/ArticlePageComponent'
export {default as ArticleDetailedComponent} from './articlePageComponent/ArticleDetailedComponent'
export {default as AboutPageComponent} from './aboutPageComponent/AboutPageComponent'
export {default as ContactPageComponent} from './contactPageComponent/ContactPageComponent'
export {default as PricingPageComponent} from './pricingPageComponent/PricingPageComponent'